<a href="https://colab.research.google.com/github/jayachandran-M-web/sentimental-analysis-in-NLP/blob/main/SentimentalAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install openai pandas nltk scikit-learn

In [ ]:
import pandas as pd
!gdown 1nemNrGqx32NfI5hpg-lW4c7oOhMqrD_i
reviews=pd.read_csv('/content/review.csv',encoding='latin1')
text=reviews['text'][0]
print(text)

Downloading...
From: https://drive.google.com/uc?id=1nemNrGqx32NfI5hpg-lW4c7oOhMqrD_i
To: /content/review.csv
100% 25.8k/25.8k [00:00<00:00, 55.3MB/s]
Waste of money, extremely dissatisfied


In [ ]:
###2.Sentimental analysis with NLTP###

import nltk
nltk.download('vader_lexicon')
from nltk.sentiment import SentimentIntensityAnalyzer

sia = SentimentIntensityAnalyzer()

score = sia.polarity_scores('Great!')
if score['compound']>0:
  print('positive')
else:
  print('negative')

positive


[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

features = reviews['text']
labels = reviews['sentiment']

X_train,X_test, Y_train, Y_test = train_test_split(features, labels, test_size=0.2, stratify=labels)

vectorizer = TfidfVectorizer()
X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

classifier = SVC()
classifier.fit(X_train,Y_train)

predictions = classifier.predict(X_test)

print(accuracy_score(Y_test,predictions))


1.0


In [1]:
import pandas as pd
import numpy as np

# Text vectorization
from sklearn.feature_extraction.text import TfidfVectorizer

# Train-test split
from sklearn.model_selection import train_test_split

# Support Vector Machine classifier
from sklearn.svm import SVC

# Evaluation metrics
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [17]:
reviews = pd.read_csv("review.csv", encoding='latin1', on_bad_lines='skip')

# Preview dataset
print(reviews.head())

                                                text sentiment
0             Waste of money, extremely dissatisfied  negative
1       The product stopped working after a few days  negative
2  The product quality is excellent and exceeded ...  positive
3     Highly recommend this, totally worth the money  positive
4                    Neither good nor bad, just fine   neutral


In [18]:
features = reviews['text']

# Label (dependent variable)
labels = reviews['sentiment']

In [19]:
X_train, X_test, y_train, y_test = train_test_split(
    features,
    labels,
    test_size=0.2,
    stratify=labels,   # Keeps class distribution balanced
    random_state=42
)

In [20]:
vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words='english',
    max_features=5000,   # Limits vocabulary size
    ngram_range=(1, 2)   # Unigrams + Bigrams
)

# Fit on training data
X_train_tfidf = vectorizer.fit_transform(X_train)

# Transform test data
X_test_tfidf = vectorizer.transform(X_test)


In [32]:
classifier = SVC(
    kernel='linear',  # Best for text classification
    C=1.0,
    random_state=42,
    probability=True
)

classifier.fit(X_train_tfidf, y_train)

SVC(kernel='linear', probability=True, random_state=42)

In [22]:
predictions = classifier.predict(X_test_tfidf)

In [23]:
accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy)

print("\nClassification Report:\n")
print(classification_report(y_test, predictions))

print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, predictions))

Accuracy: 1.0

Classification Report:

              precision    recall  f1-score   support

    negative       1.00      1.00      1.00        36
     neutral       1.00      1.00      1.00        33
    positive       1.00      1.00      1.00        31

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100


Confusion Matrix:

[[36  0  0]
 [ 0 33  0]
 [ 0  0 31]]


In [29]:
def predict_sentiment(text):
    text_vector = vectorizer.transform([text])
    prediction = classifier.predict(text_vector)[0]
    probability = classifier.predict_proba(text_vector).max()
    return prediction, probability

In [33]:
predict_sentiment("The course explanation was awful")

('negative', np.float64(0.36321236760429565))